sudo: required

services:
  - docker

script:
  - docker build --iidfile iid .
  - docker run -v $(pwd)/goss.yaml:/goss.yaml $(cat iid) sh -c 'curl -fsSL https://goss.rocks/install | sh; goss validate'

after_success:
  - LATEST_VERSION=$(docker run oxeva/phpcpd:latest phpcpd --version | awk '{print $2}')
  - PHPCPD_VERSION=$(docker run $(cat iid) phpcpd --version | awk '{print $2}')
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag $(cat iid) oxeva/phpcpd:$PHPCPD_VERSION
  - docker tag $(cat iid) oxeva/phpcpd:$(echo $PHPCPD_VERSION | cut -d. -f 1,2)
  - if [ "$(echo -e "$LATEST_VERSION\n$PHPCPD_VERSION" | sort -V | head -n1)" == "$LATEST_VERSION" ]; then
    docker tag $(cat iid) oxeva/phpcpd:latest
    fi
  - docker push oxeva/phpcpd
